services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092" # Exposed port for external clients
      - "9093:9093" # Internal broker communication port
    command: [ "sh", "-c", "kafka-storage format -t my-kraft-cluster-id -c /etc/kafka/kraft.properties; kafka-server-start /etc/kafka/kraft.properties" ]
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./container-config/kraft.properties:/etc/kafka/kraft.properties

volumes:
  kafka-data:
