process.roles=broker,controller
node.id=1
listeners=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
advertised.listeners=INSIDE://kafka:9093,OUTSIDE://localhost:9092
listener.security.protocol.map=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
inter.broker.listener.name=OUTSIDE
controller.listener.names=INSIDE
log.dirs=/var/lib/kafka/data
controller.quorum.bootstrap.servers=localhost:9093
controller.quorum.voters=1@localhost:9093
